### ISSUE TITLE
Create User

### ISSUE THREAD

**Issue by dnshariprasad** [dnshariprasad/android-new_linky#2]
Implement create user @girigiramesh 

https://new-linky.herokuapp.com
POST 
/users.json
**body :** 
{"user":{
  "first_name":"Hari",
  "last_name":"Prasad",
  "email":"hari@kvana.com",
  "mobile":"9963627839",
  "password":"hari123"
}
}

success response : 

{
  "id": 8,
  "first_name": "Hari",
  "last_name": "Prasad",
  "email": "dnshariprasad.com",
  "mobile": "9963627838",
  "password": "hari123",
  "created_at": "2016-09-16T09:35:31.612Z",
  "updated_at": "2016-09-16T09:35:31.612Z",
  "url": "https://new-linky.herokuapp.com/users/8.json"
}

error response :
{
  "status": 400,
  "error": "Email already in use."
}

**Comment by girigiramesh** [comment]
https://github.com/dnshariprasad/android-new_linky/pull/3
